### ISSUE TITLE
Project 코드 구조 질문

### ISSUE THREAD

**Issue by keonkim** [Hanul/UPPERCASE.IO#2]
```
Sample
	Sample
    	BROWSER
        COMMON
        NODE
        R
    Sample.js
```

이렇게 나눠진다고 하는데

서버쪽 폴더를 SERVER
라고 하지 않고 NODE라고 한 이유가 있나요?

SERVER/BROWSER/COMMON
또는
SERVER/CLIENT/COMMON (client는 여러가지이므로)
이렇게 구조하는것이 더 직관적이지 아닐까 합니다.

**Comment by Hanul** [comment]
예전의 UPPERCASE.IO를 보시면 말씀하신 대로 SERVER/BROWSER/COMMON으로 구조되어 있습니다.
* 1.3 버젼 문서 : http://1.3.uppercase.io/#UDOC/UPPERCASE.IO

1.4와 1.5(최종 버젼입니다. 현재는 버전 넘버링이 없습니다.)부터는 타 플랫폼으로의 확장을 꾀하고 있습니다. 따라서 추후에는 서버사이드가 node.js이지만은 않을 예정입니다. 성능을 위해 C/C++로 확장을 할 수도 있고, JVM 플랫폼이 필요해서 JVM 기반의 js 플랫폼으로 옮길 수도 있습니다.

CLIENT도 마찬가지 이유로 BROWSER로 정한 것입니다만, 사실 지금도 CLIENT 폴더를 만들어 보시면 브라우저에서 확인하실 수 있습니다 :) CLIENT는 여러 클라이언트들이 공통으로 사용하는 코드들을 모아놓을 폴더입니다. 예를들면 js로 네이티브 앱을 만드는 Titanium이나, IoT 개발에서도 최근에는 js를 사용하는 경우가 있어서 이런 것들도 고려한 것이지요.
